import pandas as pd
import numpy as np
import os
from tqdm import tqdm
import fire


def bootstrap_real(
    boot_rate: float,
    n_boot: int,
    gene: str,
    pheno_path: str,
    fam_path: str,
    covar,
    bootstrap_path: str,
    out_str: str,
    pheno_col: str = None,
    sample_id_col: str = "iid",
    seed: int = None,
):
    """
    Conduct bootstrapping for each gene. To save memory and computation time, bootstrap covariates are maintained to be the same as point estimate covariates.

    :param boot_rate: randomly sampling how many percent of the cells with replacement
    :param n_boot: number of bootstraps
    :param gene: gene name
    :param pheno_path: the path to file of gene expression and covariates, separated by comma, contains all covariates columns
    :param fam_path: path to the fam file generated by plink. The file
    :param covar: comma-separated string or list of covariates to include
    :param bootstrap_path: the path to save all the bootstrap files, assuming each gene has its own directory, e.g. bootstrap/gene/boot1/
    :param out_str: the output bootstrap file name, without adding the index of bootstrap. We will hard-code it for processing the results
    :param pheno_col: phenotype column name. Defaults to gene name.
    :param sample_id_col: sample ID column in the phenotype file.
    :param seed: optional random seed for deterministic bootstrapping.
    """

    def parse_columns(value):
        if value is None:
            return []
        if isinstance(value, str):
            return [x.strip() for x in value.split(",") if x.strip()]
        return list(value)

    print("GENE " + gene)
    if not os.path.isfile(fam_path):
        raise FileNotFoundError(f"FAM file does not exist: {fam_path}")

    covar_cols = parse_columns(covar)
    pheno_col = pheno_col or gene
    required_cols = [sample_id_col, "cid"] + covar_cols + [pheno_col]
    required_cols = list(dict.fromkeys(required_cols))

    try:
        print("Read in gene expression ... ")
        df_pheno = pd.read_csv(pheno_path, usecols=required_cols)
    except ValueError as exc:
        raise ValueError(
            f"Phenotype file {pheno_path} does not contain required columns: "
            f"{', '.join(required_cols)}"
        ) from exc

    df_fam = pd.read_csv(fam_path, usecols=[0, 1], sep=r"\s+", header=None)
    df_fam.columns = ["fam_fid", "fam_iid"]
    df_pheno = pd.merge(
        df_pheno,
        df_fam,
        left_on=sample_id_col,
        right_on="fam_iid",
        how="inner",
    )
    if df_pheno.empty:
        df_pheno = pd.merge(
            pd.read_csv(pheno_path, usecols=required_cols),
            df_fam,
            left_on=sample_id_col,
            right_on="fam_fid",
            how="inner",
        )
    df_pheno.dropna(inplace=True)
    n_cells = df_pheno.shape[0]
    n_select = int(n_cells * boot_rate)
    if n_cells == 0:
        raise ValueError("No phenotype rows matched the FAM sample IDs.")
    if n_select <= 0:
        raise ValueError("boot_rate produced zero selected cells.")

    rng = np.random.default_rng(seed)

    print("Bootstrap with replacement ...")
    for i in tqdm(range(n_boot)):
        print("Create bootstrap files")
        boot_dir = os.path.join(bootstrap_path, "boot" + str(i))
        os.makedirs(boot_dir, exist_ok=True)

        # sampling with replacement
        chosen_idx = rng.choice(n_cells, replace=True, size=n_select)
        df_boot = df_pheno.iloc[chosen_idx].copy()
        df_boot["fid"] = df_boot["fam_fid"]
        df_boot["iid"] = df_boot["fam_iid"]
        df_boot["cid"] = np.arange(1, df_boot.shape[0] + 1)
        df_boot.dropna(inplace=True)
        df_id = df_boot[["fid", "iid"]].drop_duplicates()
        df_id.to_csv(
            os.path.join(boot_dir, out_str + "_id.txt"),
            sep="\t",
            index=None,
            header=False,
        )
        out_cols = ["fid", "iid", "cid"] + covar_cols + [pheno_col]
        out_cols = list(dict.fromkeys(out_cols))
        df_boot[out_cols].to_csv(
            os.path.join(boot_dir, out_str + "_" + str(i) + ".txt"), index=None
        )


if __name__ == "__main__":
    fire.Fire(bootstrap_real)
