
#install.packages('Matrix')
library(Matrix)
library(optparse)

option_list = list(
  make_option("--grm_path", action='store', default=NA, type='character', 
              help="Path to the Sparse GRM file generated by saige. "),
  make_option("--n_marker", action='store', default=NA, type='integer', 
              help="Number of random markers used for sparse GRM. "),
  make_option("--out", action='store', default=NA, type='character', 
              help="Output path. ")
)

opt = parse_args(OptionParser(option_list=option_list))
print(opt)
print("Read param finished ...")

sparseGRMLarge = Matrix:::readMM(opt$grm_path)
print(paste0('The density proportion is ', nnzero(sparseGRMLarge)/length(sparseGRMLarge)))

# standardize
diagonal <- diag(sparseGRMLarge)
scaling_factors <- sqrt(1 / diagonal)
scaling_matrix <- Diagonal(x = scaling_factors)
standardized_sparseGRMLarge <- scaling_matrix %*% sparseGRMLarge %*% scaling_matrix

# sanity check
if (nnzero(standardized_sparseGRMLarge)/length(standardized_sparseGRMLarge) != nnzero(sparseGRMLarge)/length(sparseGRMLarge)){
  warning("Error, density proportion does not match before/after standardization.")
} 
trace_standardized <- sum(diag(standardized_sparseGRMLarge))
n_rows <- nrow(standardized_sparseGRMLarge)
print(paste0("Diagonal standardize to ", trace_standardized / n_rows))

# check invertible
# is_invertible <- function(X) !inherits(try(solve(X), silent = TRUE), "try-error")
# print(paste0("Check if new matrix is non-singular: ", is_invertible(standardized_sparseGRMLarge)))

# check singularity, if not enforce it
numIDV            <- dim(standardized_sparseGRMLarge)[1]
scalerM           <- diag(numIDV)-(rep(1,numIDV)%*%t(rep(1,numIDV)))/numIDV
eig               <- eigen(standardized_sparseGRMLarge)
eigval            <- eig$value
eigvector         <- eig$vectors
if(any(eigval<1e-10)){ 
  warning("The relatedness matrix is singular, it has been modified!")
  standardized_sparseGRMLarge_new <- as.matrix(nearPD(standardized_sparseGRMLarge,corr=T)$mat)	
}

Ms <- solve(standardized_sparseGRMLarge_new)
if(rankMatrix(standardized_sparseGRMLarge_new)[1] < numIDV){
  warning("Error, the standardized GRM is still singular!")
}

if(nnzero(standardized_sparseGRMLarge_new)/length(standardized_sparseGRMLarge_new) == 1){
    print("The new standardized GRM is not sparse anymore. ")    
}

out_str<-paste0(opt$out, '_standard_relatednessCutoff_0.125_', opt$n_marker, '_randomMarkersUsed.sparseGRM.mtx')
standardized_sparseGRMLarge_new <- as(standardized_sparseGRMLarge_new, 'sparseMatrix')
Matrix:::writeMM(standardized_sparseGRMLarge_new, out_str)
cat("Standaridization finished. ")


# Rscript trace.R --grm_path /expanse/lustre/projects/ddp412/zix016/permut_sim/500_indiv/sim_0/HM_chr1_1MB_sim0_relatednessCutoff_0.125_240_randomMarkersUsed.sparseGRM.mtx --n_marker 240 --out /expanse/lustre/projects/ddp412/zix016/permut_sim/500_indiv/sim_0/HM_chr1_1MB_sim0 

