library(Matrix)
library(optparse)

option_list = list(
  make_option("--grm_path", action='store', default=NA, type='character', 
              help="Path to the Sparse GRM file generated by saige. "),
  make_option("--n_marker", action='store', default=NA, type='integer', 
              help="Number of random markers used for sparse GRM. "),
  make_option("--out", action='store', default=NA, type='character', 
              help="Output path. ")
)

opt = parse_args(OptionParser(option_list=option_list))
print(opt)
print("Read param finished ...")

sparseGRMLarge = Matrix:::readMM(opt$grm_path)
print(paste0('The density proportion is ', nnzero(sparseGRMLarge)/length(sparseGRMLarge)))

# standardize
diagonal <- diag(sparseGRMLarge)
if (any(diagonal <= 0)) {
  stop("Sparse GRM contains non-positive diagonal entries and cannot be standardized.")
}
scaling_factors <- sqrt(1 / diagonal)
scaling_matrix <- Diagonal(x = scaling_factors)
standardized_sparseGRMLarge <- scaling_matrix %*% sparseGRMLarge %*% scaling_matrix

# sanity check
if (nnzero(standardized_sparseGRMLarge)/length(standardized_sparseGRMLarge) != nnzero(sparseGRMLarge)/length(sparseGRMLarge)){
  warning("Error, density proportion does not match before/after standardization.")
} 
trace_standardized <- sum(diag(standardized_sparseGRMLarge))
n_rows <- nrow(standardized_sparseGRMLarge)
print(paste0("Diagonal standardize to ", trace_standardized / n_rows))

# check invertible
# is_invertible <- function(X) !inherits(try(solve(X), silent = TRUE), "try-error")
# print(paste0("Check if new matrix is non-singular: ", is_invertible(standardized_sparseGRMLarge)))

# check singularity, if needed enforce positive definiteness
numIDV            <- dim(standardized_sparseGRMLarge)[1]
standardized_sparseGRMLarge_new <- standardized_sparseGRMLarge
eig               <- eigen(as.matrix(standardized_sparseGRMLarge), only.values=TRUE)
eigval            <- eig$value
if(any(eigval<1e-10)){ 
  warning("The relatedness matrix is singular, it has been modified!")
  standardized_sparseGRMLarge_new <- nearPD(standardized_sparseGRMLarge,corr=T)$mat
}

if(rankMatrix(standardized_sparseGRMLarge_new)[1] < numIDV){
  warning("Error, the standardized GRM is still singular!")
}

if(nnzero(standardized_sparseGRMLarge_new)/length(standardized_sparseGRMLarge_new) == 1){
    print("The new standardized GRM is not sparse anymore. ")    
}

out_str<-paste0(opt$out, '_standard_relatednessCutoff_0.125_', opt$n_marker, '_randomMarkersUsed.sparseGRM.mtx')
standardized_sparseGRMLarge_new <- as(standardized_sparseGRMLarge_new, 'sparseMatrix')
Matrix:::writeMM(standardized_sparseGRMLarge_new, out_str)
cat("Standardization finished. ")
